version: '3.3'

services:

    polygence-work:
        container_name: ${IMAGE_NAME}-${CONTAINER_ID}
        image: ${IMAGE_NAME}:${IMAGE_TAG}

        build:
            context: ../../
            dockerfile: ./configs/docker/Dockerfile
            args:
              PYTHON_VERSION: ${PYTHON_VERSION}
              DEBIAN_VERSION: ${DEBIAN_VERSION}
              POETRY_VERSION: ${POETRY_VERSION}

        ports:
            - '127.0.0.1:5000:5000'

        volumes:
            - ../../:/usr/user/workdir

    database:
        image: postgres:latest
        restart: always

        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}

        ports:
            - '127.0.0.1:5432:5432'

        volumes:
            - ../../.database:/data/postgres

    database-admin:
        image: dpage/pgadmin4:latest
        restart: always

        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.org
            PGADMIN_DEFAULT_PASSWORD: admin

        ports:
            - '127.0.0.1:8080:80'